__version__ = "0.0.0"
__author__ = "ExplosionAI GmbH"
__email__ = "contact@explosion.ai"
__uri__ = "https://github.com/honnibal/spacy-ray"
__license__ = "MIT"
__summary__ = "spaCy plugin for parallel processing with Ray"
